language: node_js
sudo: required
addons:
  chrome: stable
node_js:
  - "16"
before_install:
  - npm i npm@^8 -g
  - npm i yarn -g
install:
  - yarn
script:
  - npm run build
services:
  - xvfb
notifications:
  email: false
